### ISSUE TITLE
Semi-transparent entities get transformed into billboards

### ISSUE THREAD

**Issue by Tschipcraft** [bradleyq/light_painter#8]
Hello,

incredible work so far! The colored lights look amazing.
However, I found an issue with semi-transparent entities. Since you are using the rendertype_item_entity_translucent_cull core shader to transform the model into a billboard, invisible entities while using spectator mode or by setting the gamerule seeFriendlyInvisibles also get affected (Taken from the [Minecraft-Shaders-Wiki](https://github.com/McTsts/Minecraft-Shaders-Wiki/blob/main/Core%20Shader%20List.md#item_entity_translucent_cull)).

In the three screenshots, I summoned an armor stand with the NBT Invisible:1b and set my gamemode to spectator.

<table>
  <tr>
    <th width="33%">
      <img src="https://user-images.githubusercontent.com/78470530/232253840-fdbd7208-aab0-4a88-a39e-2d042d873ef1.png" alt="no rp"/>
      No resource pack
    </th>
    <th width="33%">
      <img src="https://user-images.githubusercontent.com/78470530/232253861-917feaea-0749-401d-ae71-b71b53de046d.png" alt="rp"/>
      With resource pack
    </th>
    <th width="33%">
      <img src="https://user-images.githubusercontent.com/78470530/232253876-95283912-2f38-46f2-9693-ebd1d41bbcc0.png" alt="rp + fabulous"/>
      Resource pack + Fabulous
    </th>
  </tr>
</table>

I was able to fix this myself by adding the following code after the `marker = float(texture(Sampler0, UV0).a == 1.0);` part in core/rendertype_item_entity_translucent_cull.vsh, but since I'm fairly new to core shaders this might not be sufficient:

```
ivec2 dim = textureSize(Sampler0, 0);

if (dim.x <= 1023 && dim.y <= 1023) {
    marker = 0;
}
```

Cheers, Tschipcraft

**Comment by bradleyq** [comment]
Thanks resolved in a similar fashion.
